name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to github pages
        run: |
          npm ci
          npm run build
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
