name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to github pages
        run: |
          npm ci
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm run deploy
